config/routes.rb
Rails.application.routes.draw do
  resources :venues
  devise_for :users
  resources :welcomeds

  root to: 'welcomeds#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venue.rb
# == Schema Information
#
# Table name: venues
#
#  id         :integer          not null, primary key
#  name       :string
#  rating     :float
#  address    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Venue < ApplicationRecord
end

app/models/welcomed.rb
# == Schema Information
#
# Table name: welcomeds
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Welcomed < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name, :rating, :address)
    end
end

app/controllers/welcomeds_controller.rb
class WelcomedsController < ApplicationController
  before_action :set_welcomed, only: [:show, :edit, :update, :destroy]

  # GET /welcomeds
  # GET /welcomeds.json
  def index
    @welcomeds = Welcomed.all
  end

  # GET /welcomeds/1
  # GET /welcomeds/1.json
  def show
  end

  # GET /welcomeds/new
  def new
    @welcomed = Welcomed.new
  end

  # GET /welcomeds/1/edit
  def edit
  end

  # POST /welcomeds
  # POST /welcomeds.json
  def create
    @welcomed = Welcomed.new(welcomed_params)

    respond_to do |format|
      if @welcomed.save
        format.html { redirect_to @welcomed, notice: 'Welcomed was successfully created.' }
        format.json { render :show, status: :created, location: @welcomed }
      else
        format.html { render :new }
        format.json { render json: @welcomed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomeds/1
  # PATCH/PUT /welcomeds/1.json
  def update
    respond_to do |format|
      if @welcomed.update(welcomed_params)
        format.html { redirect_to @welcomed, notice: 'Welcomed was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcomed }
      else
        format.html { render :edit }
        format.json { render json: @welcomed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomeds/1
  # DELETE /welcomeds/1.json
  def destroy
    @welcomed.destroy
    respond_to do |format|
      format.html { redirect_to welcomeds_url, notice: 'Welcomed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcomed
      @welcomed = Welcomed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcomed_params
      params.fetch(:welcomed, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/welcomeds_helper.rb
module WelcomedsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VenueShark</title>
    <%= csrf_meta_tags %>
		<!-- Custom Fonts -->

    <!-- Plugin CSS -->
   <%= stylesheet_link_tag 'magnific-popup' %>
    <link href="vendor/assets/stylesheets/creative.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>





	<body class="landing">
	  <nav class="navbar"> 
		   <a href= <%= url_for(root_path)%> class="navbar-logo">
		        <%= image_tag 'shark.png' %>
		   <a>
		    <div class="links-container">
		    	<% if current_user %>
						<p class="navbar-link"> Welcome Back, <%= current_user.email %> </p>
		    	<% else %>
		        <%= link_to "Sign In", new_user_session_path, class: "navbar-link" %>
		        <%= link_to "Sign Up", root_path, class: "navbar-link" %>
		      <% end %>
		    </div>
		</nav>
	  <%= yield %>
	</body>
</html>

app/views/venues/_form.html.erb
<%= simple_form_for(@venue) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :rating %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<div class="container-fluid main-container">

  <p id="notice"><%= notice %></p>


  <div class="venues-container row">
    <h1 align="center" class="index-title">Venues</h1>

    <%= link_to "Add Venue", new_venue_path, class: 'btn add-button' %>
  
    <% @venues.each do  |venue| %>
      <h1> <%= venue.name %></h1>
      <p> <%= venue.rating %> </p>
      <p> <%= venue.address %> </p>
    <% end %>
    <br>
  </div>
    <%= link_to 'New Venue', new_venue_path %>
</div>

app/views/venues/new.html.erb
<h1>New Venue</h1>

<%= render 'form', venue: @venue %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @venue.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @venue.rating %>
</p>

<p>
  <strong>Address:</strong>
  <%= @venue.address %>
</p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>

app/views/welcomeds/_form.html.erb
<%= form_for(welcomed) do |f| %>
  <% if welcomed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(welcomed.errors.count, "error") %> prohibited this welcomed from being saved:</h2>

      <ul>
      <% welcomed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcomeds/edit.html.erb
<h1>Editing Welcomed</h1>

<%= render 'form', welcomed: @welcomed %>

<%= link_to 'Show', @welcomed %> |
<%= link_to 'Back', welcomeds_path %>

app/views/welcomeds/index.html.erb
<body class="landing">
    <div class="hero-content"> <!--     hero content -->
        <h1 class="hero-title">Venue Shark</h1>
        <p class="hero-tagline">Listen like the locals</p>
        <% if current_user %>
          <%= link_to "Get started #{current_user.email}", venues_path , class: 'btn btn-success rawr' %>

        <% else %>

          <%= link_to "Sign Up!", new_user_registration_path, class: 'btn btn-success rawr' %>
        <% end %>
    </div>
        
    <div class="selling-points container clearfix"> <!-- selling points -->
        <div class="point column third">
            <span class="ion-music-note"></span>
            <h5 class="point-title">Choose your music</h5>
            <p class="point-description">The world is full of music; why listen to shit music?</p>
        </div>
        <div class="point column third">    
            <span class="ion-radio-waves"></span>
            <h5 class="point-title">Earn points by going to shows</h5>
            <p class="point-description">Rage out and take huge extasy pills!</p>
        </div>
        <div class="point column third">
            <span class="ion-iphone"></span>
            <h5 class="point-title">Mobile enabled</h5>
            <p class="point-description">Listen to your music on the go. This streaming service is available on all devices.</p>
        </div>
    </div>
</body>

app/views/welcomeds/new.html.erb
<h1>New Welcomed</h1>

<%= render 'form', welcomed: @welcomed %>

<%= link_to 'Back', welcomeds_path %>

app/views/welcomeds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_welcomed_path(@welcomed) %> |
<%= link_to 'Back', welcomeds_path %>